INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2000', '5022', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2001', '5023', 'Hombre de ', '21.81', '274.66');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2002', '5023', 'Mujer de ', '4.63', '204.00');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2003', '5024', '0', '5.4');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2004', '5025', '98', '279');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2005', '5026', '2.6', '4.4');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2006', '5027', 'Mujeres hasta ', '0', '38');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2007', '5027', 'Hombres hasta ', '0', '55');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2008', '5028', '70', '110');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2009', '5029', '70', '160');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2010', '5031', 'Edad gestacional 1 a 10 semanas', '44.71', '256740');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2011', '5031', 'Edad gestacional 11 a 15 semanas', '11550', '265380');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2012', '5031', 'Edad gestacional 16 a 22 semanas', '7480.8', '111566');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2013', '5031', 'Edad gestacional 23 a 40 semanas', '1531.1', '101566');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2014', '5031', 'Negativo', '0', '5');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('2015', '5032');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('2016', '5033');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2017', '5034', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2018', '5035', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2019', '5036', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2020', '5037', '65.0', '175.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2021', '5038','Aldutos de', '0.35', '5.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2022', '5039','Hombres', '0.95', '11.95');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2023', '5039','Mujeres: Fase folicular', '3.03', '8.08');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2024', '5039','Mujeres: Mitad de ciclo', '2.55', '16.69');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2025', '5039','Mujeres: Fase lútea', '1.38', '5.47');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2026', '5039','Mujeres: Posmenopáusicas', '26.72', '133.41');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2027', '5040','Hombres adultos', '0.57', '12.07');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2028', '5040','Mujeres: Fase folicular', '1.80', '11.78');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2029', '5040','Mujeres: Mitad de ciclo', '7.59', '89.08');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2030', '5040','Mujeres: Fase lútea', '0.56', '14.00');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2031', '5040','Posmenopáusicas sin TRH', '5.16', '61.99');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2032', '5041','Adultos de', '6.33', '12.40');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2033', '5042', '540', '1822');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2034', '5043', '63', '484');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2035', '5044', '6', '27');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2036', '5045', '8', '78');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2037', '5046', '1.8', '2.4');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2038', '5047','Negativo hasta', '0', '50');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2039', '5048','No Detectado / Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2040', '5049','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2041', '5050','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2042', '5051','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2043', '5052', '20', '50');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2044', '5054','Varones', '261', '462');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2045', '5054','Mujeres', '265', '497');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2046', '5055', '200', '360');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2047', '5056', '60', '150');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2048', '5057', '33', '293');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2049', '5059','Mujeres de', '35', '150');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2050', '5059','Hombres de', '40', '160');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2051', '5060', '35', '50');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2052', '5061', '0', '150');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2053', '5062', '20', '26');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2054', '5064','Positivo >', '0', '2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2055', '5064','Negativo <', '0', '2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2056', '5065','Negativo <', '0', '2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2057', '5065','Intermedio', '2', '2.6');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2058', '5065','Positivo >', '0', '2.6');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2059', '5066','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2060', '5067','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2061', '5068','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2062', '5069','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2063', '5070','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2064', '5071','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2065', '5072','Hombres', '11', '44');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2066', '5072','Mujeres con menstruación normal: Fase filicular', '21', '251');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2067', '5072','Mujeres con menstruación normal: Fase mitad de ciclo', '38', '649');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2068', '5072','Mujeres con menstruación normal: Fase luteinica', '21', '312');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2069', '5072','Mujeres posmenopáusicas no sometidas a terapia de reemplazo hormonal (TRH) <', '10', '28');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2070', '5072','Mujeres posmenopáusicas sometidas a terapia de reemplazo hormonal (TRH) <', '10', '144');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2071', '5075','Hombres', '3.46', '19.40');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2072', '5075','Mujeres', '5.18', '26.53');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2073', '5076','Hombres <', '0.1', '0.2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2074', '5076','Mujeres con menstruación: Fase folicular <', '0.1', '0.3');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2075', '5076','Mujeres con menstruación: Fase lúteinica', '1.2', '15.9');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2076', '5076','Mujeres posmenopáusicas <', '0.1', '0.2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2077', '5076','Mujeres embarazadas: Primer trimestre', '2.8', '147.3');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2078', '5076','Mujeres embarazadas: Segundo trimestre', '22.5', '95.3');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2079', '5076','Mujeres embarazadas: Tercer trimestre', '27.9', '242.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2080', '5077','Hombres (edad): 21 - 49 años', '47.01', '980.56');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2081', '5077','Hombres (edad): Igual o mayor de 50 años', '127.18', '1020.36');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2082', '5077','Mujeres (edad): 21 - 49 años', '7.21', '79.31');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2083', '5077','Mujeres (edad): Igual o mayor de 50 años', '8.65', '36.92');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2084', '5078','Mujeres', '0', '4.2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2085', '5079','NEGATIVO', '0', '1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2086', '5079','POSITIVO', '1', '100');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2087', '5080','NEGATIVO', '0', '1.4');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2088', '5080','POSITIVO', '1.4', '100');


INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3001', '6001', '4.51', '3.51');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_min`) VALUES ('3002', '6002', 'Normal <', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3003', '6002', 'Politraumatismo, Quemaduras', '0.25', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3004', '6002', 'Infecciones bacterianas gravez', '0.5', '0.25');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3005', '6002', 'Septicemia, Fracaso multiorgánico >', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3006', '6004', 'NEGATIVO hasta', '3');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3007', '6005', 'Menor a ', '5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3008', '6006', 'Hasta', '40');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3009', '6007', 'Hasta', '41');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3010', '6009', '50', '35');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3011', '6010', '35', '20');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3012', '6011', '2.2', '1.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3013', '6013', 'Hasta', '1');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3014', '6015', '414', '207');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3015', '6023', '45', '15');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3016', '6024', 'Mujeres de', '1.1', '0.6');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3017', '6024', 'Hombres de', '1.4', '0.7');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3018', '6025', 'Mujeres de', '6.0', '2.6');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3019', '6025', 'Hombres de', '7.2', '3.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3020', '6026', '5.0', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3021', '6027', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3022', '6028', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3023', '6029', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3024', '6030', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3025', '6031', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3026', '6032', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3027', '6033', '143.7', '133.7');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3028', '6034', 'Adultos de ', '3.18', '1.88');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3029', '6035', 'De ', '162.0', '58.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3030', '6036', 'Adultos de', '1.4', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3031', '6037', 'Adultos de', '14.5', '5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3032', '6041', 'Negativo hasta', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3033', '6042', '44.0', '15.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3034', '6043', 'Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3035', '6044', 'Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3036', '6045', 'Deficiente < ', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3037', '6045', 'Insuficiente', '30', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3038', '6045', 'Suficiente', '100', '30');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_min`) VALUES ('3039', '6045', 'Toxicidad potencial >', '100');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3040', '6046', 'Hombres de ', '22', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3041', '6046', 'Mujeres de ', '29', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3042', '6047', 'Adultos de ', '6.0', '2.0');