INSERT INTO contents (`content_id`, `content_name`) VALUES ('4002', 'CAPACIDAD DE FIJACION DE HIERRO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4003', 'SEGMENTADOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4006', 'EOSINOFILOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4007', 'Impresion Hormonal');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4008', 'Impresion de Maduracion');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4009', 'Efecto Estrogenico');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4010', 'Efecto progestacional');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4011', 'Flora bacteriana');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4012', 'Leucocitos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4013', 'Eritrocitos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4014', 'Agentes infectantes');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4015', 'Otros elementos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4016', 'Celulas del Epitelio Ectocervical y Vaginal');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4017', 'Células de Metaplasia');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4018', 'Células Endocervicales');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4019', 'Resultado');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4020', 'Clasificacion general');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4021', 'Calidad de la muestra');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4022', 'COLOR');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4023', 'ASPECTO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4024', 'PH');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4025', 'GLUCOSA');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4026', 'PROTEINAS TOTALES');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4027', 'CLORO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4028', 'CELULARIDAD');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4030', 'LINFOCITOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4031', 'MONOCITOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4032', 'POLIMORFONUCLEARES');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4033', 'CK-MB');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4035', 'COLESTEROL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4036', 'COMPLEMENTO HEMOLITICO C3');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4037', 'COMPLEMENTO HEMOLITICO C4');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4038', 'Amikacina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4039', 'Ampicilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4040', 'Carbenicilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4041', 'Cefalotina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4042', 'Cefotaxima');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4043', 'Ceftamicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4044', 'Cefuroxima');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4045', 'Ciprofloxacina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4046', 'Clindamicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4047', 'Cloranfenicol');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4048', 'Dicloxacilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4049', 'Eritromicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4050', 'Fosfomicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4051', 'Gentamicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4052', 'Netilmicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4053', 'Nitrofurantoina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4054', 'Norfloxacina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4055', 'Penicilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4056', 'Tetraciclina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4057', 'Trimetropim/Sulfametoxasol');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4058', 'Vancomicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4059', 'Consistencia');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4060', 'Olor');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4061', 'Alimentos sin digerir');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4062', 'Moco');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4063', 'Sangre visible');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4064', 'Sangre oculta en heces');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4065', 'Azucares reductores');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4066', 'Almidones');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4067', 'Grasas');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4068', 'Parasitos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4069', 'Amiba en fresco - platina caliente');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4070', 'Levaduras');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4072', 'Mononucleares');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4073', 'CORTISOL MATUTINO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4074', 'CORTISOL VESPERTINO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4075', 'CPK');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4076', 'CREATIN FOSFO CINASA TOTAL - CPK');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4077', 'Creatin Fosfo Cinasa Total-CPK');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4079', 'Glucosa 1 (en ayuno)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4080', 'Glucosa 2 (a la hora)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4081', 'Glucosa 3 (a las 2 horas)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4082', 'DEHIDROEPIANDROSTERONA (DHEA)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4083', 'Depuracion de creatinina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4084', 'Volumen de orina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4085', 'Creatinina en orina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4086', 'Creatinina serica');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4090', 'DIMERO D');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4094', 'Calcio');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4097', 'Hora de emision');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4098', 'Hora de inicio del examen');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4099', 'Viscosidad');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4100', 'Licuefacción');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4101', 'Volumen');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4102', 'Grado de Movilidad');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4103', 'Lineal rapida');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4104', 'Lineal lenta');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4105', 'Moviles');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4106', 'Inmoviles');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4109', 'Celulas epiteliales');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4110', 'Bacterias');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4111', 'Mucina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4114', 'Aglutinacion cabeza con cabeza');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4115', 'Aglutinacion segmento intermedio con segmento intermedio');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4116', 'Aglutinacion cola con cola');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4117', 'Aglutinacion mixta');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4118', 'Zoospermos viables');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4119', 'Zoospermos no viables');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4120', 'Numero de zoospermos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4122', 'TROFOZOITOS QUISTES');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4123', 'HUEVECILLOS PROGLOTIDES GRÁVIDOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4124', 'HUEVECILLOS LARVAS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4125', 'DENSIDAD');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4126', 'ESTEREASA LEUCOCITARIA');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4127', 'PROTEINAS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4128', 'MICROALBUMINA');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4129', 'CETONAS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4130', 'BILIRRUBINAS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4131', 'NITRITOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4132', 'UROBILINOGENO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4133', 'SANGRE');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4134', 'CELULAS DEL EPITELIO ESCAMOSO (uretra, vagina)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4135', 'CELULAS DEL EPITELIO RENAL (tubulo renal)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4136', 'CELULAS EPITELIALES DE TRANSICIÓN (vejiga, ureteros, pelvis renal)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4137', 'BACTERIAS (BACILOS)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4138', 'BACTERIAS (COCOS)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4139', 'CILINDROS GRANULOSOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4140', 'CILINDRO HIALINOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4142', 'ERITROCITOS EUMORFICOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4143', 'ERITROCITOS DISMÓRFICOS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4144', 'CRISTALES');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5022', 'Factor Reumatoide');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5023', 'FERRITINA');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5024', 'FOSFATASA ACIDA TOTAL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5025', 'FOSFATASA ALCALINA');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5026', 'FOSFORO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5027', 'GGT (Gamma Glutamil Transpeptidasa)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5028', 'Glucosa en ayuno');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5029', 'Glucosa Postprandial');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5031', 'Cuantificación de Gonadotropina Corionica Fracción Beta');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5032', 'Grupo Sanguíneo');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5033', 'RH Sanguíneo');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5034', 'Hepatitis ‘A’');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5035', 'Hepatitis ‘B’');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5036', 'Hepatitis ‘C’');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5037', 'HIERRO SÉRICO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5038', 'Hormona Estimulante de Tiroides (TSH)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5039', 'HORMONA FOLÍCULO ESTIMULANTE (FSH)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5040', 'HORMONA LUTEINIZANTE (LH)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5041', 'Índice de Tiroxina Libre (ITL, FTI)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5042', 'INMUNOGLOBULINA G (IgG)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5043', 'INMUNOGLOBULINA M (IgM)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5044', 'INSULINA BASAL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5045', 'Lipasa');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5046', 'MAGNESIO');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5047', 'MIOGLOBINA');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5048', 'PCR VIRUS Sars Cov-2 (Covid - 19)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5049', 'Antigeno NS1');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5050', 'Anticuerpos Anti Dengue IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5051', 'Anticuerpos Anti Dengue IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5052', '% De saturación de hierro');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5054', 'Capacidad de Fijación de Hierro (TIBC)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5055', 'Transferrina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5056', 'HIERRO LIBRE');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5057', 'INMUNOGLOBULINA A (IgA)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5059', 'Triglicéridos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5060', 'Colesterol HDL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5061', 'Colesterol LDL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5062', 'Colesterol VLDL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5064', 'Ac. Anti Toxoplasmosis IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5065', 'Ac. Anti toxoplasmosis IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5066', 'Rubeola IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5067', 'Rubeola IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5068', 'Citomegalovirus (CMV) IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5069', 'Citomegalovirus (CMV) IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5070', 'Herpes simple 1/2 (HSV 1/2) IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5071', 'Herpes simple 1/2 (HSV 1/2) IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5072', 'Estradiol (E2)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5075', 'Prolactina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5076', 'Progesterona');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5077', 'Testosterona Total');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5078', 'Testosterona libre');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5079', 'ANTICUERPOS IgM SARS - CoV-2');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5080', 'ANTICUERPOS IgG SARS - CoV-2');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6001', 'POTASIO', 'mmol/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6002', 'PROCALCITONINA','ng/mL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6004', 'Proteína C reactiva','mg/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6005', 'PROTEINA C REACTIVA CUANTIFICADA','mg/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6006', 'TGO (Aspartao amino transferasa)','U/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6007', 'TGP  (Alanino amino transferasa)','U/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6009', 'Albumina','g/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6010', 'Globulina','g/L');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6011', 'Relacion Albumina Globulina');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6012', 'Bilirribina Total','mg/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6013', 'Bilirrubina Directa','mg/dL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6014', 'Bilirrubina Indirecta');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6015', 'DHL (Deshidrogenasa lactica)','U/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6023', 'Urea','mg/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6024', 'Creatinina','mg/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6025', 'Ácido Úrico','mg/dL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6026', 'Índice aterogénico');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6027', 'SALMONELLA TIFICO “O”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6028', 'SALMONELLA TIFICO “H”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6029', 'SALMONELLA PARATÍFICO “A”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6030', 'SALMONELLA PARATÍFICO “B”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6031', 'BRUCELLA ABORTUS');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6032', 'PROTEUS OX-19');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6033', 'SODIO','mmol/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6034', 'T3 Libre','pg/ml');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6035', 'T3 Total (Triyodotironina)','ng/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6036', 'T4 Libre','ng/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6037', 'T4 Total','ug/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6041', 'TROPONINA','ng/mL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6042', 'T-UPTAKE (TU)','%');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6043', 'V.D.R.L');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6044', 'V.I.H. (Virus de Inmunodeficiencia Humana)');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6045', 'VITAMINA D (25-HIDROXI-COLECALCIFEROL)','ng/mL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6046', 'Velocidad de Sedimentación Globular','mm / Hr');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6047', 'Yodo Proteico (IP)','ug/dL');