INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('1000', '4002', 'Varones','462','261');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('1001', '4002', 'Mujeres','497','265');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1003', '4003');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1004', '4006');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1005', '4007');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1006', '4008');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1007', '4009');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('1008', '4010','mmol/L','105.0','93.0');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1009', '4011');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1010', '4012','5 por campo');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1011', '4013');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1012', '4014');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1013', '4015');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1014', '4016');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1015', '4017');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1016', '4018');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1017', '4019');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1018', '4020');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1019', '4021');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('1020', '4022','Variable - Transparente');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1021', '4023','Variable');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1022', '4024','8.0','5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1023', '4025','92','52');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1024', '4026','3.0','0');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1025', '4027','93.0 a 105.0 mmol/L');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`)VALUES ('1026','4028','MENOS DE 300/ML');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1027', '4030');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1028', '4031');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1029', '4032');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('1030', '4033','Negativo hasta 5 ng/mL');
INSERT INTO reference (`idreferences`, `content_id`,`v_max`, `v_min`) VALUES ('1031', '4035', '200','0');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1032', '4036','193.0','83.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1033', '4037','57.0','15.0');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1034', '4038');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1035', '4039');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1036', '4040');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1037', '4041');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1038', '4042');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1039', '4043');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1040', '4044');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1041', '4045');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1042', '4046');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1043', '4047');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1044', '4048');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1045', '4049');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1046', '4050');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1047', '4051');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1048', '4052');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1049', '4052');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1050', '4053');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1051', '4054');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1052', '4055');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1053', '4056');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1054', '4057');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1055', '4058');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1056', '4059','Variable');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1057', '4060','Variable');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1058', '4061','No observados');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1059', '4062','No observados');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1060', '4063','No observados');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1061', '4064','Negativo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1062', '4065','Negativo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1063', '4066','Negativo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1064', '4067','Negativo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1065', '4068','No observados');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1066', '4069','No observadas');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1067', '4070','No observadas');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1068', '4072');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`, `v_max`, `v_min`) VALUES ('1069', '4073','Matutino (Antes de las 10:00 h)','626','123');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`, `v_max`, `v_min`) VALUES ('1070', '4074','Vespertino (Después de las 17:00 h)','389','46.2');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1071', '4075','59','14');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1072', '4076','24','0');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1073', '4077','Hombres hasta 195 U/L');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1074', '4077','Mujeres hasta 170U/L');
INSERT INTO reference (`idreferences`, `content_id`,`v_max`, `v_min`) VALUES ('1075', '4079','110','60');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1076', '4080','Hasta 200');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1077', '4081','Hasta 140');
INSERT INTO reference (`idreferences`, `content_id`,`v_max`, `v_min`) VALUES ('1078', '4082','10.30','0.49');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`, `v_max`, `v_min`) VALUES ('1079', '4083','ml/min','107','82');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`, `v_max`, `v_min`) VALUES ('1080', '4084','ml/24 hrs','2000','800');
INSERT INTO reference (`idreferences`, `content_id`,`v_max`, `v_min`) VALUES ('1081', '4085','259','39');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1082', '4086','1.18','0.73');
INSERT INTO reference (`idreferences`, `content_id`,`v_max`, `v_min`) VALUES ('1083', '4090','0.50','0.00');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('1084', '4094','1.11','0.91');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('1085', '4097','Procesamiento inmediato');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('1086', '4098','Procesamiento inmediato');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('1087', '4099','Gotas bien definidas');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('1088', '4100','00/30-60/00');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`) VALUES ('1089', '4101','1.5-5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('1090', '4102','Grado A - B');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1091', '4103');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1092', '4104');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1093', '4105');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1094', '4106');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1095', '4109','0.0- 0.0');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1096', '4110','0.0- 0.0');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1097', '4111','0.0- 0.0');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1098', '4114');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1099', '4115');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1100', '4116');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1101', '4117');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1102', '4118');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1103', '4119');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1104', '4120');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1105', '4122');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1106', '4123');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1107', '4124');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1108', '4125');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1109', '4126');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1110', '4127');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1111', '4128');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1112', '4129');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1113', '4130');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1114', '4131');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1115', '4132');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1116', '4133');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1117', '4134','3 a 5 por campo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1118', '4135','Ausentes');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1119', '4136','0 a 1 por campo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1120', '4137','Ausentes');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1121', '4138','Ausentes');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1122', '4139','Ausentes');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1123', '4140','Hasta 3 por campo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1124', '4142','3 a 5 por campo');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1125', '4143','Ausentes');
INSERT INTO reference (`idreferences`, `content_id`,`v_ref_text`) VALUES ('1126', '4144','Ausentes');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1127', '4168');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1128', '4169');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1129', '4170');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1130', '4171');

INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1131', '4172');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1132', '4173');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1133', '4174');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1134', '4175');

INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1135', '4176');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1136', '4177');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1137', '4178');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1138', '4179');

INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1139', '4145');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1140', '4146');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1141', '4147');

INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1142', '4148');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1143', '4149');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1144', '4150');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1145', '4151');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1146', '4152');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1147', '4153');

INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1148', '4154');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1149', '4155');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1150', '4156');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1151', '4157');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1152', '4158');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1153', '4159');

INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1154', '4160');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1155', '4161');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1156', '4162');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1157', '4163');

INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1158', '4164');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1159', '4165');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1160', '4166');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('1161', '4167');


INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2000', '5022', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2001', '5023', 'Hombre de ', '274.66', '21.81');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2002', '5023', 'Mujer de ', '204.00', '4.63');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2003', '5024', '5.4','0');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2004', '5025', '279', '98');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2005', '5026', '4.4', '2.6');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2006', '5027', 'Mujeres hasta ', '38', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2007', '5027', 'Hombres hasta ', '55', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2008', '5028', '110', '70');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2009', '5029', '160', '70');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2010', '5031', 'Edad gestacional 1 a 10 semanas', '256740', '44.71');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2011', '5031', 'Edad gestacional 11 a 15 semanas', '265380', '11550');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2012', '5031', 'Edad gestacional 16 a 22 semanas', '111566', '7480.8');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2013', '5031', 'Edad gestacional 23 a 40 semanas', '101566', '1531.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2014', '5031', 'Negativo', '5', '0');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('2015', '5032');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('2016', '5033');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2017', '5034', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2018', '5035', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2019', '5036', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2020', '5037', '175.0', '65.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2021', '5038','Aldutos de', '5.1', '0.35');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2022', '5039','Hombres', '11.95', '0.95');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2023', '5039','Mujeres: Fase folicular', '8.08', '3.03');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2024', '5039','Mujeres: Mitad de ciclo', '16.69', '2.55');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2025', '5039','Mujeres: Fase lútea', '5.47', '1.38');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2026', '5039','Mujeres: Posmenopáusicas', '133.41', '26.72');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2027', '5040','Hombres adultos', '12.07', '0.57');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2028', '5040','Mujeres: Fase folicular', '11.78', '1.80');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2029', '5040','Mujeres: Mitad de ciclo', '89.08', '7.59');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2030', '5040','Mujeres: Fase lútea', '14.00', '0.56');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2031', '5040','Posmenopáusicas sin TRH', '61.99', '5.16');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2032', '5041','Adultos de', '12.40', '6.33');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2033', '5042', '1822', '540');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2034', '5043', '484', '63');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2035', '5044', '27', '6');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2036', '5045', '78', '8');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2037', '5046', '2.4', '1.8');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2038', '5047','Negativo hasta', '50', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2039', '5048','No Detectado / Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2040', '5049','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2041', '5050','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2042', '5051','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2043', '5052', '50', '20');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2044', '5054','Varones', '462', '261');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2045', '5054','Mujeres', '497', '265');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2046', '5055', '360', '200');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2047', '5056', '150', '60');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2048', '5057', '293', '33');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2049', '5059','Mujeres de', '150', '35');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2050', '5059','Hombres de', '160', '40');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2051', '5060', '50', '35');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2052', '5061', '150', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('2053', '5062', '26', '20');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2054', '5064','Positivo', '2', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2055', '5064','Negativo', '2', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2056', '5065','Negativo', '2', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2057', '5065','Intermedio', '2.6', '2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2058', '5065','Positivo', '2.6', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2059', '5066','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2060', '5067','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2061', '5068','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2062', '5069','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2063', '5070','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('2064', '5071','NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2065', '5072','Hombres', '44', '11');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2066', '5072','Mujeres con menstruación normal: Fase filicular', '251', '21');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2067', '5072','Mujeres con menstruación normal: Fase mitad de ciclo', '649', '38');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2068', '5072','Mujeres con menstruación normal: Fase luteinica', '312', '21');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2069', '5072','Mujeres posmenopáusicas no sometidas a terapia de reemplazo hormonal (TRH)', '28', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2070', '5072','Mujeres posmenopáusicas sometidas a terapia de reemplazo hormonal (TRH)', '144', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2071', '5075','Hombres', '19.40', '3.46');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2072', '5075','Mujeres', '26.53', '5.18');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2073', '5076','Hombres <', '0.2', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2074', '5076','Mujeres con menstruación: Fase folicular <', '0.3', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2075', '5076','Mujeres con menstruación: Fase lúteinica', '15.9', '1.2');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2076', '5076','Mujeres posmenopáusicas <', '0.2', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2077', '5076','Mujeres embarazadas: Primer trimestre', '147.3', '2.8');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2078', '5076','Mujeres embarazadas: Segundo trimestre', '95.3', '22.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2079', '5076','Mujeres embarazadas: Tercer trimestre', '242.5', '27.9');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2080', '5077','Hombres (edad): 21 - 49 años', '980.56', '47.01');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2081', '5077','Hombres (edad): Igual o mayor de 50 años', '1020.36', '127.18');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2082', '5077','Mujeres (edad): 21 - 49 años', '79.31', '7.21');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2083', '5077','Mujeres (edad): Igual o mayor de 50 años', '36.92', '8.65');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2084', '5078','Mujeres', '4.2', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2085', '5079','NEGATIVO', '1', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2086', '5079','POSITIVO', '100', '1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2087', '5080','NEGATIVO', '1.4', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('2088', '5080','POSITIVO', '100', '1.4');


INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3001', '6001', '4.51', '3.51');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_min`) VALUES ('3002', '6002', 'Normal <', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3003', '6002', 'Politraumatismo, Quemaduras', '0.25', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3004', '6002', 'Infecciones bacterianas gravez', '0.5', '0.25');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3005', '6002', 'Septicemia, Fracaso multiorgánico >', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3006', '6004', 'NEGATIVO hasta', '3');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3007', '6005', 'Menor a ', '5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3008', '6006', 'Hasta', '40');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3009', '6007', 'Hasta', '41');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3010', '6009', '50', '35');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3011', '6010', '35', '20');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3012', '6011', '2.2', '1.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3013', '6012', 'Hasta', '1');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3014', '6015', '414', '207');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3015', '6023', '45', '15');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3016', '6024', 'Mujeres de 0.6 - 1.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3017', '6024', 'Hombres de 0.7 - 1.4');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3018', '6025', 'Mujeres de 2.6 - 6.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3019', '6025', 'Hombres de 3.5 - 7.2');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3020', '6026', '5.0', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3021', '6027', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3022', '6028', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3023', '6029', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3024', '6030', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3025', '6031', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3026', '6032', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3027', '6033', '143.7', '133.7');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3028', '6034', 'Adultos de ', '3.18', '1.88');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3029', '6035', 'De ', '162.0', '58.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3030', '6036', 'Adultos de', '1.4', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3031', '6037', 'Adultos de', '14.5', '5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3032', '6041', 'Negativo hasta', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3033', '6042', '44.0', '15.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3034', '6043', 'Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3035', '6044', 'Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3036', '6045', 'Deficiente < ', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3037', '6045', 'Insuficiente', '30', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3038', '6045', 'Suficiente', '100', '30');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_min`) VALUES ('3039', '6045', 'Toxicidad potencial >', '100');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3040', '6046', 'Hombres de ', '22', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3041', '6046', 'Mujeres de ', '29', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3042', '6047', 'Adultos de ', '6.0', '2.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3043', '6048', 'NEGATIVO / POSITIVO');
INSERT INTO reference (`idreferences`, `content_id`) VALUES ('3044', '6014');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3045', '6013', 'Hasta', '0.2');
