INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1001', 'CALCIO', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1002', 'CAPACIDAD DE FIJACION DE HIERRO', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1003', 'CITOLOGIA DE MOCO NASAL MUESTRA 1', '100');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1004', 'CITOLOGIA DE MOCO NASAL MUESTRA 3', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('1005', 'CITOLOGIA VAGINAL EXFOLIATIVA PAPANICOLAOU', '450', '400');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1006', 'CITOQUIMICO DE LIQUIDO DE ASCITIS O PERRITONEAL', '650');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1007', 'CK-MB', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1008', 'CLORO', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1009', 'COLESTEROL', '80');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1010', 'COMPLEMENTO HEMOLITICO C3', '400');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1011', 'COMPLEMENTO HEMOLITICO C4', '400');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1012', 'COPROCULTIVO CON ANTIBIOGRAMA', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('1013', 'COPROLOGICO COMPLETO', '350', '280');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1014', 'CORTISOL MATUTINO', '350');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1015', 'CORTISOL VESPERTINO', '350');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1016', 'CPK', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1017', 'CREATIN FOSFO CINASA FRACCION MB-CK-MB', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1018', 'CREATIN FOSFO CINASA TOTAL - CPK', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1019', 'CREATININA', '80');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1020', 'CULTIVO DE ESPECTORACION O ESPUTO CON ANTIBIOGRAMA', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('1021', 'CURVA DE TOLERANCIA A LA GLUCOSA', '280', '250');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1022', 'DEHIDROEPIANDROSTERONA (DHEA)', '650');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('1023', 'DEPURACION DE CREATINA EN ORINA DE 24 HRS', '200', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1024', 'DHL', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1025', 'DIMERO D', '750');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('1026', 'ELECTROLITOS SERICOS', '280', '230');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1027', 'ESPERMACULTIVO CON ANTIBIOGRAMA' , '350');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1028', 'ESPERMOGRAMA-ESPERMATOBIOSCOPIA', '400');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1029', 'ESTRADIOL (E2)', '250');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1030', 'ESTUDIO COPROPARASITOSCOPICO 1 MUESTRA', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1031', 'ESTUDIO COPROPARASITOSCOPICO 3 MUESTRAS', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('1032', 'EXAMEN GENERAL DE ORINA EGO', '80', '70');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('1033', 'EXUDADO FARINGEO CON ANTIBIOGRAMA', '350', '270');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('1034', 'EXUDADO URETRAL CON ANTIBIOGRAMA', '350');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('2001', 'EXUDADO VAGINAL CON ANTIBIOGRAMA', '350', '270');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2002', 'FACTOR REUMATOIDE', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2003', 'FERRITINA', '350');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2004', 'FOSFATASA ACIDA TOTAL', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2005', 'FOSFATASA ALCALINA', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2006', 'FOSFORO', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2007', 'GGT', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('2008', 'GLUCOSA PRE Y POSPRANDIAL', '150', '100');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2009', 'GLUCOSA', '80');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2010', 'GONADOTROPINA CORIONICA FRACCION BETA','0');
INSERT INTO tests (`idtests`, `test_name`,`test_price`) VALUES ('2011', 'GRUPO Y RH','0');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2012', 'HEPATITIS A', '400');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2013', 'HEPATITIS B', '400');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2014', 'HEPATITIS C', '400');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2015', 'HIERRO SERICO', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2016', 'HORMONA ESTIMULANTE DE TIROIDES (TSH)', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2017', 'HORMONA FOLICULO ESTIMULANTE (FSH)', '250');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2018', 'HORMONA LUTEINIZANTE (LH)', '250');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2019', 'INDICE DE TIROXINA LIBRE (ITL, FTI)', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2020', 'INMUNOGLOBULINA G (IgG)', '1500');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2021', 'INMUNOGLOBULINA M (IgM)', '1500');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2022', 'INSULINA BASAL', '350');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2023', 'LIPASA', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2024', 'MAGNESIO', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2025', 'MIOGLOBINA', '750');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2026', 'PCR VIRUS Sars Cov-2 (Covid - 19)', '2200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2027', 'PERFIL DE DENGUE DUO (Acs IgG e IgM, Ag NS1) Cualitativo','0');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2028', 'PERFIL DE HIERO + TRANSFERRINA', '900');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2029', 'PERFIL DE HIERO', '800');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2030', 'PERFIL DE INMUNOGLOBULINAS  (IgA, IgG, IgM)', '800');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2031', 'PERFIL DE LIPIDOS', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('2032', 'PERFIL DE TORCH', '2500', '800');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2033', 'PERFIL HORMONAL GINECOLOGICO','0');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('2034', 'PERFIL SEROLOGICO DE ANTICUERPOS IgM e IgG SARS CoV-2 (INDEX)','0');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3001', 'PROCALCITONINA', '800');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3002', 'PROGESTERONA', '250');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3003', 'PROTEINA C REACTIVA', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3004', 'PROTEINA C REACTIVA CUANTIFICADA', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3005', 'PRUEBA DE EMBARAZO', '120', '90');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3006', 'PRUEBAS DE FUNCIONAMIENTO HEPATICO 1', '280', '230');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3007', 'PRUEBAS DE FUNCIONAMIENTO HEPATICO 2', '300', '230');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3008', 'PRUEBAS DE FUNCIONAMIENTO HEPATICO 3', '300', '230');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3009', 'QUIMICA DE 3 MAS PERFIL DE LIPIDOS', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3010', 'QUIMICA SANGUINEA DE 3 ELEMENTOS (GLU UREA CREA)', '150', '100');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3011', 'QUÍMICA SANGUÍNEA DE 3 ELEMENTOS (GLU COL TRI)', '150', '120');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3012', 'QUÍMICA SANGUÍNEA DE 6 ELEMENTOS', '250', '230');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3013', 'QUÍMICA SANGUÍNEA DE 6 ELEMENTOS MÁS PERFIL DE LÍPIDOS', '400', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3014', 'QUÍMICA SANGUÍNEA DE 12 ELEMENTOS', '450', '350');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3015', 'REACCIONES FEBRILES', '200', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3016', 'SODIO', '140');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3017', 'T3 LIBRE', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3018', 'T3 TOTAL', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3019', 'T4 LIBRE', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3020', 'T4 TOTAL', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3021', 'TESTOSTERONA LIBRE', '250');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3022', 'TESTOSTERONA TOTAL', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3023', 'TGO', '100');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3024', 'TGP', '100');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3025', 'TRANSFERRINA', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3026', 'TRIGLICERIDOS', '80');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3027', 'TROPONINA', '800');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3028', 'T-UPTAKE (TU)', '200');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3029', 'UREA', '80');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3030', 'V.D.R.L', '80');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3031', 'VIH', '150');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3032', 'VITAMINA D (25-HIDROXI-COLECALCIFEROL)', '650');
INSERT INTO tests (`idtests`, `test_name`, `test_price`, `test_price_with_discount`) VALUES ('3033', 'VSG', '150', '80');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3034', 'YODO PROTEICO (IP)', '300');
INSERT INTO tests (`idtests`, `test_name`, `test_price`) VALUES ('3035', 'POTASIO', '150');
