INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4002', 'Capacidad de Fijación de Hierro','ug/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4003', 'Muestra 1 Citología de Moco Nasal- Fosa Nasal Derecha - Segmentados','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4006', 'Muestra 1 Citología de Moco Nasal- Fosa Nasal Derecha - Eosinofilos','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4007', 'Impresion Hormonal','-');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4008', 'Indice de Maduracion', '-');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4009', 'Efecto Estrogenico', '-');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4010', 'Efecto Progestacional', '-');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4011', 'Flora Bacteriana');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4012', 'Leucocitos','Cel/Campo');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4013', 'Eritrocitos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4014', 'Agentes infectantes');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4015', 'Otros Elementos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4016', 'Celulas del Epitelio Ectocervical y Vaginal');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4017', 'Células de Metaplasia');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4018', 'Células Endocervicales');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4019', 'Resultado');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4020', 'Clasificacion General');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4021', 'Calidad de la Muestra');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4022', 'Color');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4023', 'Aspecto');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4024', 'PH');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4025', 'Glucosa','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4026', 'Proteinas Totales', 'g/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4027', 'Cloro','mmol/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4028', 'Celularidad','cel/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4030', 'Muestra 1 Citología De Moco Nasal - Fosa Nasal Derecha - Linfocitos','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4031', 'Muestra 1 Citología De Moco Nasal - Fosa Nasal Derecha - Monocitos','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4032', 'Polimorfonucleares ','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4033', 'CK-MB', 'ng/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4035', 'Colesterol', 'mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4036', 'Complemento Hemolitico C3','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4037', 'Complemento Hemolitico C4','mg/dL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4038', 'Amikacina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4039', 'Ampicilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4040', 'Carbenicilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4041', 'Cefalotina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4042', 'Cefotaxima');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4043', 'Ceftamicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4044', 'Cefuroxima');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4045', 'Ciprofloxacina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4046', 'Clindamicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4047', 'Cloranfenicol');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4048', 'Dicloxacilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4049', 'Eritromicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4050', 'Fosfomicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4051', 'Gentamicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4052', 'Netilmicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4053', 'Nitrofurantoina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4054', 'Norfloxacina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4055', 'Penicilina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4056', 'Tetraciclina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4057', 'Trimetropim/Sulfametoxasol');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4058', 'Vancomicina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4059', 'Consistencia');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4060', 'Olor');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4061', 'Alimentos sin digerir');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4062', 'Moco');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4063', 'Sangre visible');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4064', 'Sangre oculta en heces');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4065', 'Azucares reductores');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4066', 'Almidones');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4067', 'Grasas');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4068', 'Parasitos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4069', 'Amiba en fresco - platina caliente');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4070', 'Levaduras');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4072', 'Mononucleares');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4073', 'Cortison Matutino','nmol/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4074', 'Cortisol Vespertino','nmol/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4075', 'CPK','U/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4076', 'Creatin Fosfo Cinasa Total - MB-CK-MB','U/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4077', 'Creatin Fosfo Cinasa Total - CPK','U/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4079', 'Glucosa 1 (en ayuno)','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4080', 'Glucosa 2 (a la hora)','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4081', 'Glucosa 3 (a las 2 horas)','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4082', 'Dehidroepiandrosterona (DHEA)','ng/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4083', 'Depuracion de Creatinina','mL/min');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4084', 'Volumen de Orina','mL/24 hrs');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4085', 'Creatinina en Orina','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4086', 'Creatinina Serica','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4090', 'Dimero D','ug FEU/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4094', 'Calcio','mmol/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4097', 'Hora de Emision','Hr/Min/seg');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4098', 'Hora de Inicio del Examen','Hr/Min/Seg');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4099', 'Viscosidad');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4100', 'Licuefacción','Hr/Min/Seg');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4101', 'Volumen','mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4102', 'Grado de Movilidad','Grados %');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4103', 'Lineal Rapida');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4104', 'Lineal Lenta');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4105', 'Moviles');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4106', 'Inmoviles');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4109', 'Celulas Epiteliales', 'Cel/campo');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4110', 'Bacterias','Cel/campo');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4111', 'Mucina', 'Cel/campo');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4114', 'Aglutinacion Cabeza con Cabeza','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4115', 'Aglutinacion Segmento Intermedio con Segmento Intermedio','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4116', 'Aglutinacion Cola con Cola','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4117', 'Aglutinacion Mixta','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4118', 'Zoospermos Viables','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4119', 'Zoospermos no Viables','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4120', 'Numero de Zoospermos','Cel/pL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4122', 'Muestra 1 Protozoarios Trofozoítos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4123', 'Muestra 1 Protozoarios Quistes');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4124', 'Muestra 1 Platelmientos Huevecillos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4125', 'Densidad');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4126', 'Esterasa Leucocitaria');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4127', 'Proteinas');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4128', 'Microalbumina');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4129', 'Cetonas');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4130', 'Bilirrubinas');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4131', 'Nitritos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4132', 'Urobilinógeno');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4133', 'Sangre');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4134', 'Células Del Epitelio Escamoso (uretra, vagina)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4135', 'Células Del Epitelio Renal (tubulo renal)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4136', 'Células Epiteliales De Transición (vejiga, ureteros, pelvis renal)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4137', 'Bacterias (BACILOS)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4138', 'Bacterias (COCOS)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4139', 'Cilindros Granulosos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4140', 'Cilindro Hialinos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4142', 'Eritrocitos Eumorficos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4143', 'Eritrocitos Dismórficos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4144', 'Cristales')
;
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4145', 'Muestra 1 Platelmintos Proglótides Grávidos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4146', 'Muestra 1 Nematelmintos Huevecillos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4147', 'Muestra 1 Platelmintos Larvas');

INSERT INTO contents (`content_id`, `content_name`) VALUES ('4148', 'Muestra 2 Protozoarios Trofozoitos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4149', 'Muestra 2 Protozoarios Quistes');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4150', 'Muestra 2 Platelmintos Huevecillos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4151', 'Muestra 2 Platelmintos Proglótides Grávidos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4152', 'Muestra 2 Nematelmintos Huevecillos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4153', 'Muestra 2 Platelmintos Larvas');

INSERT INTO contents (`content_id`, `content_name`) VALUES ('4154', 'Muestra 3 Protozoarios Trofozoitos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4155', 'Muestra 3 Protozoarios Quistes');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4156', 'Muestra 3 Platelmintos Huevecillos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4157', 'Muestra 3 Platelmintos Proglótides Grávidos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4158', 'Muestra 3 Nematelmintos Huevecillos');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('4159', 'Muestra 3 Platelmintos Larvas');

INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4160', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Derecha - SEGMENTADOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4161', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Derecha - EOSINOFILOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4162', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Derecha - LINFOCITOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4163', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Derecha - MONOCITOS','%');

INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4164', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Derecha - SEGMENTADOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4165', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Derecha - EOSINOFILOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4166', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Derecha - LINFOCITOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4167', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Derecha - MONOCITOS','%');

INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4168', 'Muestra 1 Citologia de Moco Nasal- Fosa Nasal Izquierda - SEGMENTADOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4169', 'Muestra 1 Citologia de Moco Nasal- Fosa Nasal Izquierda - EOSINOFILOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4170', 'Muestra 1 Citologia de Moco Nasal- Fosa Nasal Izquierda - LINFOCITOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4171', 'Muestra 1 Citologia de Moco Nasal- Fosa Nasal Izquierda - MONOCITOS','%');

INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4172', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Izquierda - SEGMENTADOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4173', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Izquierda - EOSINOFILOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4174', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Izquierda - LINFOCITOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4175', 'Muestra 2 Citologia de Moco Nasal- Fosa Nasal Izquierda - MONOCITOS','%');

INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4176', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Izquierda - SEGMENTADOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4177', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Izquierda - EOSINOFILOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4178', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Izquierda - LINFOCITOS','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('4179', 'Muestra 3 Citologia de Moco Nasal- Fosa Nasal Izquierda - MONOCITOS','%');

INSERT INTO contents (`content_id`, `content_name`) VALUES ('5022', 'Factor Reumatoide');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5023', 'Ferritina','ng/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5024', 'Fosfatasa Acida Total','U/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5025', 'Fosfatasa Alcalina','U/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5026', 'Fosforo','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5027', 'GGT (Gamma Glutamil Transpeptidasa)','U/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5028', 'Glucosa en Ayuno','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5029', 'Glucosa Postprandial','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5031', 'Cuantificación de Gonadotropina Corionica Fracción Beta','mUI/mL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5032', 'Grupo Sanguíneo');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5033', 'RH Sanguíneo');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5034', 'Hepatitis ‘A’');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5035', 'Hepatitis ‘B’');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5036', 'Hepatitis ‘C’');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5037', 'Hierro Sérico','ug/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5038', 'Hormona Estimulante de Tiroides (TSH)','uUI/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5039', 'Hormona Folículo Estimulante (FSH)','mUI/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5040', 'Hormona Luteinizante (LH)','mUI/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5041', 'Índice de Tiroxina Libre (ITL, FTI)','ug/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5042', 'Inmunoglobulina G (IgG)','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5043', 'Inmunoglobulina M (IgM)','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5044', 'Insulina Basal','uUI/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5045', 'Lipasa','U/L');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5046', 'Magnesio','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5047', 'Mioglobina','ng/mL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5048', 'PCR VIRUS Sars Cov-2 (Covid - 19)');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5049', 'Antigeno NS1');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5050', 'Anticuerpos Anti Dengue IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5051', 'Anticuerpos Anti Dengue IgM');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5052', '% De Saturación de Hierro','%');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5054', 'Capacidad de Fijación de Hierro (TIBC)','ug/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5055', 'Transferrina','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5056', 'Hierro Libre','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5057', 'Inmunoglobulina A (IgA)','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5059', 'Triglicéridos','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5060', 'Colesterol HDL','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5061', 'Colesterol LDL','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5062', 'Colesterol VLDL','mg/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5064', 'Ac. Anti Toxoplasmosis IgG','UI/mL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5065', 'Ac. Anti Toxoplasmosis IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5066', 'Rubeola IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5067', 'Rubeola IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5068', 'Citomegalovirus (CMV) IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5069', 'Citomegalovirus (CMV) IgM');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5070', 'Herpes Simple 1/2 (HSV 1/2) IgG');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5071', 'Herpes Simple 1/2 (HSV 1/2) IgM');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5072', 'Estradiol (E2)','pg/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5075', 'Prolactina','ng/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5076', 'Progesterona','ng/mL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5077', 'Testosterona Total','ng/dL');
INSERT INTO contents (`content_id`, `content_name`,`content_units`) VALUES ('5078', 'Testosterona Libre','pg/mL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5079', 'Anticuerpos IgM SARS - CoV-2');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('5080', 'Anticuerpos IgG SARS - CoV-2');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6001', 'Potasio', 'mmol/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6002', 'Procalcitonina','ng/mL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6004', 'Proteína C Reactiva','mg/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6005', 'Proteína C Reactiva Cuantificada','mg/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6006', 'TGO (Aspartao Amino Transferasa)','U/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6007', 'TGP  (Alanino Amino Transferasa)','U/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6009', 'Albumina','g/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6010', 'Globulina','g/L');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6011', 'Relacion Albumina Globulina');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6012', 'Bilirrubina Total','mg/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6013', 'Bilirrubina Directa','mg/dL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6014', 'Bilirrubina Indirecta');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6015', 'DHL (Deshidrogenasa lactica)','U/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6023', 'Urea','mg/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6024', 'Creatinina','mg/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6025', 'Ácido Úrico','mg/dL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6026', 'Índice aterogénico');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6027', 'Salmonella Tifico “O”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6028', 'Salmonella Tifico “H”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6029', 'Salmonella Paratifico “A”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6030', 'Salmonella Paratifico “B”');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6031', 'Brucella Abortus');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6032', 'PROTEUS OX-19');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6033', 'sodio','mmol/L');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6034', 'T3 Libre','pg/mL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6035', 'T3 Total (Triyodotironina)','ng/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6036', 'T4 Libre','ng/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6037', 'T4 Total','ug/dL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6041', 'Troponina','ng/mL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6042', 'T-UPTAKE (TU)','%');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6043', 'V.D.R.L');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6044', 'V.I.H. (Virus de Inmunodeficiencia Humana)');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6045', 'Vitamina D (25-HIDROXI-COLECALCIFEROL)','ng/mL');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6046', 'Velocidad de Sedimentación Globular','mm/Hr');
INSERT INTO contents (`content_id`, `content_name`, `content_units`) VALUES ('6047', 'Yodo Proteico (IP)','ug/dL');
INSERT INTO contents (`content_id`, `content_name`) VALUES ('6048','Prueba inmunológica de embarazo en sangre');