INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3001', '6001', '4.51', '3.51');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_min`) VALUES ('3002', '6002', 'Normal <', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3003', '6002', 'Politraumatismo, Quemaduras', '0.25', '0.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3004', '6002', 'Infecciones bacterianas gravez', '0.5', '0.25');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3005', '6002', 'Septicemia, Fracaso multiorgánico >', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3006', '6004', 'NEGATIVO hasta', '3');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3007', '6005', 'Menor a ', '5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3008', '6006', 'Hasta', '40');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3009', '6007', 'Hasta', '41');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3010', '6009', '50', '35');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3011', '6010', '35', '20');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3012', '6011', '2.2', '1.1');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3013', '6013', 'Hasta', '1');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3014', '6015', '414', '207');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3015', '6023', '45', '15');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3016', '6024', 'Mujeres de', '1.1', '0.6');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3017', '6024', 'Hombres de', '1.4', '0.7');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3018', '6025', 'Mujeres de', '6.0', '2.6');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3019', '6025', 'Hombres de', '7.2', '3.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3020', '6026', '5.0', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3021', '6027', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3022', '6028', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3023', '6029', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3024', '6030', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3025', '6031', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3026', '6032', 'NEGATIVO');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3027', '6033', '143.7', '133.7');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3028', '6034', 'Adultos de ', '3.18', '1.88');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3029', '6035', 'De ', '162.0', '58.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3030', '6036', 'Adultos de', '1.4', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3031', '6037', 'Adultos de', '14.5', '5.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3032', '6041', 'Negativo hasta', '0.5');
INSERT INTO reference (`idreferences`, `content_id`, `v_max`, `v_min`) VALUES ('3033', '6042', '44.0', '15.0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3034', '6043', 'Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`) VALUES ('3035', '6044', 'Negativo');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`) VALUES ('3036', '6045', 'Deficiente < ', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3037', '6045', 'Insuficiente', '30', '10');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3038', '6045', 'Suficiente', '100', '30');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_min`) VALUES ('3039', '6045', 'Toxicidad potencial >', '100');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3040', '6046', 'Hombres de ', '22', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3041', '6046', 'Mujeres de ', '29', '0');
INSERT INTO reference (`idreferences`, `content_id`, `v_ref_text`, `v_max`, `v_min`) VALUES ('3042', '6047', 'Adultos de ', '6.0', '2.0');